name = "GeoMapping"
uuid = "855c05df-eed8-5362-a099-6b509f53b81a"
keywords = ["spherical geometry", "Earth"]
license = "MIT"
desc = "Mapping function on the Earth surface with minimal dependencies"
version = "0.1.0"


[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
